FROM grpc/go:1.0

# Change this path!
WORKDIR /go/src/go-kube/frontend
ADD front* ./
COPY pb /go/src/go-kube/gcd/pb


RUN go get -v ./...
RUN go install -v ./...

EXPOSE 3001
RUN go build front.go
CMD [ "./front" ]